[build]
  command = "npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ':(exclude).env.local'"

[build.environment]
  NEXT_PUBLIC_ZALO_CLIENT_ID = ""
  NEXT_PUBLIC_ZALO_CLIENT_SECRET = ""
  NEXT_PUBLIC_ZALO_REDIRECT_URI = ""
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
